name: CI
 
on:
  - pull_request
  - push
  
jobs:
  tests:
      name: Tests
 
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
          
        - name: Setup PHP with Xdebug
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            coverage: xdebug
            
        - name: Install dependencies with composer
          run: composer update --no-ansi --no-interaction --no-progress
          
        - name: Generate key
          run: php artisan key:generate
        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache
        - name: Create Database
          run: |
            mkdir -p database
            touch database/database.sqlite
        - name: npm 
          run: npm install 
        - name: Execute tests (Unit and Feature tests) via PHPUnit
          env:
            DB_CONNECTION: sqlite
            DB_DATABASE: database/database.sqlite
          run: vendor/bin/pest --coverage-clover=coverage.xml
          
        - name: Fix code coverage paths
          run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}